name: RSpec
on: push

jobs:
  rspec:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Ruby 2.3
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.5.tar.bz2
          tar xjf ruby-2.3.5.tar.bz2
          cd ruby-2.3.5 && ./configure && make -j 2
          sudo make install
      - uses: actions/checkout@v2
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-hbx_enteprise-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-hbx_enterprise-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          sudo gem install bundler -v '1.17.3'
          bundle config path vendor/bundle
          bundle install
      - name: run tests
        run: |
          cp config/exchange.yml.example config/exchange.yml
          bundle exec rspec
