name: RSpec
on: push

jobs:
  rspec:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Packages for Ruby Prerequisites
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git libntirpc-dev libxml2 libxml2-dev curl libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev
      - name: Install libssl1.0-dev from bionic sources
        run: |
          echo 'deb http://security.ubuntu.com/ubuntu bionic-security main' | sudo tee -a /etc/apt/sources.list.d/bionic-security.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
          sudo apt update && apt-cache policy libssl1.0-dev
          sudo apt-get -y install libssl1.0-dev
      - name: Set up Ruby 2.3
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.5.tar.bz2
          tar xjf ruby-2.3.5.tar.bz2
          cd ruby-2.3.5 && ./configure && make -j 2
          sudo make install
      - uses: actions/checkout@v2
      - name: Install Bundler and Rake
        run: |
          sudo gem install bundler -v '1.17.3'
          sudo gem install rake -v '10.4.2'
      - name: Fetch and Patch Sigar
        run: |
          gem fetch sigar --version=0.7.3 && gem unpack sigar-0.7.3.gem && rm sigar-0.7.3.gem
          cd sigar-0.7.3 && patch -p1 < ../gem_patches/sigar-0.7.3.patch
          rake gem && cd ../
      - name: Install patched Sigar
        run: |
          cp ./sigar-0.7.3/pkg/sigar-0.7.3.gem ./ && sudo gem install sigar-0.7.3.gem
      - name: Install Gems
        run: |
          bundle install
      - name: run tests
        run: |
          cp config/exchange.yml.example config/exchange.yml
          bundle exec rspec
